### ISSUE TITLE
Add GitHub ribbon to every page

### ISSUE THREAD

**Issue by diegobfernandez** [urbas/budPage#1]
I struggled finding a link to source code in the Home Page of Bud.
Of course it's easily found with a little search, but that is not ideal.

**Comment by urbas** [comment]
Good idea, I'll try to get something up asap.

Do you maybe know of a fine example of such a ribbon?

**Comment by diegobfernandez** [comment]
I was thinking about these ribbons
https://github.com/blog/273-github-ribbons

**Comment by urbas** [comment]
I tried the ribbon, but it covers existing links (see screenshot).

I'll try to find another icon that can be placed into the header and into the content. Do you maybe know of any alternatives to ribbons?

![ribbon](https://cloud.githubusercontent.com/assets/771193/7314086/b2bdea26-ea58-11e4-8993-b7dde5b4e473.PNG)

**Comment by diegobfernandez** [comment]
Maybe in the menu itself.
![bud-menu](https://cloud.githubusercontent.com/assets/2291571/7322417/4bf36804-ea7e-11e4-8a44-08ff0b25bad6.png)
![bud-menu-mobile](https://cloud.githubusercontent.com/assets/2291571/7322418/4bf7ce30-ea7e-11e4-99d6-ae95ddc89343.png)
![bud-menu-mobile-expanded](https://cloud.githubusercontent.com/assets/2291571/7322419/4c070404-ea7e-11e4-8f6a-8ce453747757.png)

**Comment by diegobfernandez** [comment]
Just another suggestion :smile:
Add a link to the hosted page and bud repository in the description.
Something like: Bud's (https://github.com/urbas/bud) home page (http://bud.urbas.si/About).
Or as links: [Bud's](https://github.com/urbas/bud) [home page](http://bud.urbas.si/About).
But I'm not sure if description accepts Markdown.
EDIT: I suggest here because I think it's too little for another issue

**Comment by urbas** [comment]
Alright, I added the source code link to the page.

I also added links to repo descriptions.

Btw, it seems like the descriptions don't take Markdown.

I'll close this issue for now. Just reopen it if the solution is not okay.

**Comment by diegobfernandez** [comment]
Nice. Now it's easier to navigate.
Thanks
